### PR TITLE
Executable refactoring and no_std support

### LINKED ISSUE #76: Make gas metering injection and stack height limiter work in no_std
Related https://github.com/paritytech/parity-wasm/issues/209

### PR DESCRIPTION
**Pull request by sorpaas**
* Move executables to separate crates. In this way, we can get minimal dependencies for core util library.
* Add no_std support for core util library. In particular, `BTree` map and set will be used when in no_std.
* Temporarily depend on git version of parity-wasm until no_std is released.

Closes #76

### CODE REVIEW

**Comment by fckt** [comment]
just tried to `cargo install`.`cargo install` is not looking trough workspace for binaries. 
```
cargo install
error: no packages found with binaries or examples
```
I'm not sure, maybe it will still work in case if we install it from crates.io though

**Comment by sorpaas** [comment]
@fckt Yeah looks like after splitting the executable, it would need to be installed individually. https://github.com/rust-lang/cargo/issues/4101

**Comment by NikVolf** [comment]
we will have to publish every binary package separately?

**Comment by sorpaas** [comment]
@NikVolf Yes, but we can also combine it together. Which way do we prefer?

**Comment by NikVolf** [comment]
Yeah, i think all executables should be in one place at least )

**Comment by fckt** [comment]
We should make sure the install command will continue to work. Otherwise we have to edit `.travis.yml`'s in all projects which are using `wasm-build`

**Comment by pepyakin** [comment]
Great!

**Comment by pepyakin** [comment]
But can we release parity-wasm and use the released version there?

**Pull request merged**
