### PR TITLE
Add build_with_constructor and build_raw

### PR DESCRIPTION
**Pull request by fckt**
`build_with_constructor` and `build_raw` was introduced to have a more sound API

### CODE REVIEW

**Comment by NikVolf** [comment]
can you explain "more sound" ?

**Comment by fckt** [comment]
> can you explain "more sound" ?

It's clearly expressed by this change https://github.com/paritytech/wasm-utils/pull/99/files#diff-96a3339c3b514b4ecc2cc0380cddde2eL177

Does it need step-by-step explanation?

**Comment by fckt** [comment]
> proper update for this api would be creating something like Config object for build function used the following way:

makes sense

**Comment by fckt** [comment]
So, what I don't like in current API is that I have to check if `module_ctor` is not `None`, even is I know that it shouldn't (because I set `true` in `build` before). So the question is, how

```
let config = BuildConfig::new().source(SourceTarget::Unknown).constructor();
build(config)?;
```

would allow to me to solve this problem?

**Comment by NikVolf** [comment]
I don’t think solving this little problem worth iterating over the api with breaking changes

You can use generics for build function, and return generic result

**Comment by fckt** [comment]
> I don’t think solving this little problem 

I'd better to hide little problems inside. Just imagine: users have to copy and paste over and over again this message:
```
ctor_module.expect("ctor_module can't be None, because 'constructor' argument is set to true in build"),
```

> worth iterating over the api with breaking changes

I don't see any breaking changes. `build` still there (but I rather think better to remove it, I don't think too many users are managed to take advantage of `build` API after 20 hours of it's handiness).

> You can use generics for build function, and return generic result

An example would be helpful.

**Comment by NikVolf** [comment]
> I don't see any breaking changes. 

There will be some, once we want to implement BuildConfig, and since the api surface will be larger, there will be much more breaking changes.

Right now it is just a copy from cli functionality, it is ok for now

Any further changes should be thoughtful and in one PR

**Pull request closed without merging**
